### ISSUE TITLE
Feature suggestion: help in the hidden level Treacherous Crossing

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#14]
I have noticed that the Treacherous Crossing has only a few different possibilities. Maybe players would be happy to have a slash command such as /ah crossing that would list the different combinations. Or /ah crossing 1 would list the combinations beginning by the first switch (from left to right).

So far, here are the combinations I've noticed:

```
1  5  4 2L 3  6
2  5  1 4  3
3R 1  4 6  5L 2
3  5  1 4  2L 6
5  1  4 2  3
5  1  4 2  3  6
5  2L 6 4  3R 1 
5R 3  4 1  2  6
```

L or R means turning left or right at a fork in the road. I don't know if it widely known or not but it would probably be a good helper ;)

**Comment by Stemuweb** [comment]
> Whoops - should be ok now

We did a quick test outside the archive, data sharing and debug prints are back but it doesn't change the drop-downs values of the other player. Note: if the drop-downs are not designed for, maybe they should be disabled and not updated for the non-leader, and he should just see the solutions.

**Comment by Flat-Badger-1971** [comment]
The capability is there - just something wrong with the response to the data share - I'll look into it

**Comment by Flat-Badger-1971** [comment]
OK - reworked the response, should hopefully work better now

**Comment by Stemuweb** [comment]
No, still no result on the other player's panel. I'll try to add some debug prints after data reception, to see  if I can provide some information on this problem.

**Comment by Stemuweb** [comment]
Two minor details:

1. You are testing AH.Vars.ShowHelper in ShowCrossingHelper(). So, the player can't use the keybind or the slash command at all until they activate the setting. I'd rather thought that the setting meant that the helper opened up by itself in the hidden level.
I'd rather check AH.Vars.ShowHelper in the function zoneCheck() to condition the call to the ShowCrossingHelper().

2. If the helper can't be opened via the keybind or the / command, it would be user-friendly to display a log message to explain why, otherwise the player might think that the add-on isn't working properly or that he's typed an incorrect command (That's the first thing that happened to me this morning when I logged on to Summerset to do my craft).
The message should explain the helper can only be used in the Treacherous Crossing level in the Infinite Archive. (and/or if the setting is on or not, depending on how point 1 is resolved)

**Comment by Flat-Badger-1971** [comment]
ok - should now have accounted for all the above - fingers crossed...

**Comment by Stemuweb** [comment]
Data sharing was working. No error by transferring leadership. Will retry shortly in real conditions, in the archive without debug ode.

L(AH .. "CROSSING_INVALID", "L'aide ne peut être activée qu'à l'intérieur du Gué traître dans l'Archive Infinie")

**Comment by Stemuweb** [comment]
Another small suggestion about the settings: REMINDER_QUEST (option[12]) could be moved up in the menu to be grouped with REMINDER ([7]). Both are reminder texts that can happen everywhere in the archival wing. Then everything related to hidden levels would follow.

**Comment by Flat-Badger-1971** [comment]
Awesome - thanks again for all the testing. Just done another push with your last two comments

**Comment by Stemuweb** [comment]
> Awesome - thanks again for all the testing. Just done another push with your last two comments

My pleasure. And thank you for your continued patience in sorting out the small details.

I may have made a mistake and got the index wrong. I shouldn't be typing suggestions while I'm playing. You moved up the SHOW_CROSSING_HELPER setting, instead REMINDER_QUEST. It should have been index 11 and not 12, perhaps. Sorry for the confusion.

**Comment by Flat-Badger-1971** [comment]
Ha - I didn't even bother looking at the text, I just used the numbers - that will teach me to pay more attention :-)

**Comment by Stemuweb** [comment]
It looks good now. Great idea to have added a "target markers" section, it makes the settings more distinct and easier to find. I would swap GW_PLAY and GW_MARKER (17 and 18), so that marker can be found before play, because "play" can be disabled by "marker" , hence is secondary.

Also a swap of MARAUDER_INCOMING_PLAY and MARAUDER_MARKER (19 and 20) because now that the section is about markers, it's more logic to present the marker first.

I promise to stop after that. Beautiful, well-organised UIs are my guilty pleasure.

**Comment by Flat-Badger-1971** [comment]
I appreciate attention to detail - the only reason I have them the current way around is so the marauder icon is at the bottom of the list, otherwise it looks a little out of place. That being said, your idea makes more sense - I'll give it some thought.

**Comment by Flat-Badger-1971** [comment]
OK - I've thought about it :) I've moved the icon to the other side of the text

**Comment by Stemuweb** [comment]
No luck tonight. 3 arcs, we got every hidden level except the (aptly named) treacherous crossing.

I noted that the tomeshells count did not take into account the plural. There are two calls in functions tomeCheck(), startTomeCheck() that still use the first version of the formatter:
`local message = zo_strformat(_G.SI_SCREEN_NARRATION_TIMER_BAR_DESCENDING_FORMATTER, tomesLeft)`
instead of 
`local message = zo_strformat(_G.ARCHIVEHELPER_TOMESHELL_COUNT, tomesLeft)`

**Comment by Stemuweb** [comment]
Unless it's an emergency, I suggest not doing a release for the moment. I've noticed a quirk with the drop-down lists: they're not updated visually when data is received, but the value is taken into account logically for future filtering.

I would like to properly test whether they are correctly disabled for the non-leader and whether they reset if leadership is transferred, which would hide the problem with drop-downs.

**Comment by Stemuweb** [comment]
Another small settings adjustment: SHARD_IGNORE (16) should be disabled if SHARD_MARKER (15) is off.

Question/bug: currently, SHARD_IGNORE and SHARD_MARKER settings are disabled if "not AH.CompatibilityCheck()". Is it correct? I remember you said Lykeon's add-on should only disable Fabled detection.

**Comment by Flat-Badger-1971** [comment]
All sorted - another push done to github

**Comment by Stemuweb** [comment]
Still no luck tonight. No Treacherous crossing but so many goat levels (over 10 since yesterday!)

We switched to debug mode and tested with the / command. It works well overall (data sharing, drop-downs disabled for the non-leader, change of leader detected).

However, can you confirm that it's not possible to visually update the drop-down lists programmatically when data is received?

This leads to a small bug in this case:

1. The group leader (A) chooses [5] [1] [_] (begin, 2nd and last)
2. Both players see 2 solutions but the other player B still sees his selections as empty: [_] [_] [_]
3. A transfers leadership to B _(we've kept the panels open. I don't know if this would also happen with closed panels)_
4. B selects the value 3 as the end of the path. The only solution appears in both players' panel but B only sees [_] [_] [3]. This is very confusing (the logic values are taken into account but it doesn't match what is visible).

Ideally, the drop-down menus should be visually updated, but you'd probably have done that already if it were possible.

To avoid this confusion, you'd at least have to reset both players' selectors when the lead changes. I hope this is at least technically possible.

Otherwise, as a last resort, close the panels to force a rebuild... (I say this having no idea how the UI works in this game).

I admit it's a case that should only happen exceptionally, but one of the players might prefer to be the one handling the drop-downs while the other inspects the switches, and they'll want to pass the lead to each other, so it would be better to make sure it doesn't look buggy.

**Comment by Stemuweb** [comment]
https://github.com/Flat-Badger-1971/ArchiveHelper/issues/14#issuecomment-2028514157

As seen in my first draft of the UI (a long time ago!), I had in mind to highlight the elements of the path that correspond to the values in the drop-down lists. I didn't want to bother you with that at the moment, so I tried it out to see if it was feasible.

I tested the blue colour used by "possible paths" but in the end I preferred the yellow, which balances out the title at the top and the drop-down lists in the middle.

I'll let you try it out and see what you think visually. No problem if you don't like it, it's only an 'embellishment'  and I could do without it. Otherwise, you can probably rewrite it in a more optimal way (the number conversions are already done above for the "test" variable, there might be a way to store and reuse them, etc).

**Comment by Stemuweb** [comment]
Also (and it will be my last enhancement for the helper): since french needs 4 lines of text and I have room for a few more words, I suggest to add this at the end of the instructions: **", until only one solution remains."** I just want to be the clearer possible so that no one has difficulty understanding the how and why.

```
L(
    AH .. "CROSSING_INSTRUCTIONS2",
    "Find the switch corresponding to the start of the path and select it in the dropdown below (1 is the leftmost switch, 6 the rightmost)." ..
        " Then, if necessary, find the 2nd step or the end of the path, until only one solution remains."
)
L(
    AH .. "CROSSING_INSTRUCTIONS",
    "Trouvez l'interrupteur correspondant au début du chemin et sélectionnez-le dans la liste déroulante ci-dessous (1 est le plus à gauche, 6 le plus à droite)." ..
        " Puis, si nécessaire, trouvez la 2ème étape ou la fin du chemin, jusqu'à ce qu'il ne reste qu'une solution."
)
```

I checked the length in both languages and it fits. The german translation is not set yet (but a fifth line of text will not overlap with the content below instructions anyway)

**Comment by Stemuweb** [comment]
The helper works well! Two small points:
1. the keybind should close it even if you are not in the Treacherous crossing (but it should be useless because of point 2)
2. the panel should close when leaving the crossing anyway

**Comment by Flat-Badger-1971** [comment]
1. You're correct - I'll sort that
2. It should automatically close when you succeed for fail at the crossing based on the following values appearing in your screen announcements - they are currently missing from the French (and German) translations:

> L(AH .. "CROSSING_FAIL", "Locked")

> L(AH .. "CROSSING_SUCCESS", "Solved")

**Comment by Stemuweb** [comment]
Thank you. I'll update them as soon as I can

**Comment by Flat-Badger-1971** [comment]
Yep, saw 14 and implemented it almost verbatim.

**Comment by Stemuweb** [comment]
Almost done

L(AH .. "CROSSING_FAIL", "Failed")
L(AH .. "CROSSING_SUCCESS", "Solved") -- You Solved the Corridor Puzzle

L(AH .. "CROSSING_FAIL", "verrouillé")
L(AH .. "CROSSING_SUCCESS", "résolu") -- Vous avez résolu l'énigme du couloir

L(AH .. "CROSSING_FAIL", "Failed")
L(AH .. "CROSSING_SUCCESS", "gelöst") -- Ihr habt des Rätsel der Gänge gelöst

**Comment by Stemuweb** [comment]
I'll do a final test on this translated branch that include all your latest code. I'll remove the **debug mode**.

If you want to do a release on minion, better not change anything at the last minute (except translation corrections of course)

And remove **debug mode** in the release ;D (so subtle...)

**Comment by Flat-Badger-1971** [comment]
Added your translations. I'll ask the guy who did the original German translations to double check, but he doesn't seem to be on much.

Also, if you see lines like this:
``-- luacheck: ignore 631

Could you make sure they stay where they are in the file please? They don't affect functionality, but they do stop VS Code complaining about things like 'line too long' in the translations. I use LuaCheck for linting and find it very handy.

**Comment by Flat-Badger-1971** [comment]
I installed luacheck from here: https://github.com/mpeterv/luacheck
Then I use it in conjuction with the vscode-lua extension and an ever-evolving .luacheckrc file
