### ISSUE TITLE
Suggestion: display a warning in duo mode if optional libraries are missing

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#16]
When beginning the archival wing, if in duo mode, if the player has set the specific keybind or actived a setting that uses data sharing, it would be nice to display something like :

`Warning: LibDataShare is not available. [if the keybinds are set]Setting target marks manually may malfunction. [if the corresponding option is on] The count of remaining tomeshells in the Filer's wing won't update properly.`

Maybe add a setting too to opt out of the warning, in case some people would be annoyed by it:

`Display a warning when optional libraries are missing: yes/no`

**Comment by Flat-Badger-1971** [comment]
Added a warning if either of the libs is missing. It will appear at the top of the settings page

**Comment by Stemuweb** [comment]
Would it be possible to add a linefeed as a separator between the strings (with a table concat separator perhaps, in case more messages would be added in the future... It will make your code more complex, but it would be easier to read: see screenshot below)

![settings warning with LF](https://github.com/Flat-Badger-1971/ArchiveHelper/assets/27444797/6ce7ab7b-b5ee-4916-b7ac-a87502a83f3d)

**Comment by Flat-Badger-1971** [comment]
Good idea - done.
