### ISSUE TITLE
Bug: minor gender/plural bug in timer/counter

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#30]
In French, the Echoing den timer displays: "Xs restant". There is no agreement with the gender (in this case feminine) and the number (should end with an -s if the number is not 1).

It should be "0s restant**es** | 1s restant**e** | 2s restant**es**".

For the filer's wing, the counter shows: "X restant". 

It should be "0 restant**s** | 1 restant | 2 restant**s**" (tomeshell is masculine. Yay, French!)

There's probably a similar problem in German (but gender may differ). I read Zos has [modifiers](https://wiki.esoui.com/How_to_format_strings_with_zo_strformat#Pluralisation) for plural and gender but I don't know if it's easy to incorporate.

This bug is only cosmetic and can be ignored if it takes more than 5 minutes to fix.

**Comment by Flat-Badger-1971** [comment]
Easiest way to resolve this is to add a couple of entries to the fr.lua file, which I've done. There's format that looks like this:
`<<1[0s restantes/1s restante/$ds restantes]>>`
It automatically selects the correct one based on the number it's given.
