### ISSUE TITLE
Minor bug in Gw's sound triggering

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#34]
Description:

- Player A has the setting AH.Vars.GwPlay off -- they don't want to hear the alert
- Player B has the setting AH.Vars.GwPlay on -- they would like to hear it
- Player A marks Gw, neither player hears the sound

Expected: player B must hear the sound, regardless of A's setting.

The data should be shared by A anyway, when Gw is marked. Player B can then decide whether to play the alert or not.

https://github.com/Flat-Badger-1971/ArchiveHelper/blob/64cfe3f211dc0dffc39fe7eaad86f8d0457eae1b/misc/markers.lua#L155-L159

I think that the AH.Vars.GwPlay test should only condition the call to PlayAlarm().

---

Also, a small detail related to the topic:

`L(AH .. "GW_PLAY", "Play warning when Gw appears")`

The word "appears" could confuse some players. Not knowing the intricacies of the API, they might think that the add-on is capable of detecting the Pilferer as effectively as the Marauders, and will probably complain in the comments that it is sometimes not detected immediately.

I'd suggest a change. For example:

`Play warning when Gw is marked / when marking Gw`

And in french:

`Jouer un son quand Gw est marqué`

Edit: I hope it doesn't bother too much the german translator!

**Comment by Flat-Badger-1971** [comment]
Yep - correct on both counts - I'll get that into the next push
