### ISSUE TITLE
Suggestion: renaming arc and phase boss reminder

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#35]
I noticed german has slightly different messages:

L(AH .. "ARC_BOSS", "Tho’at Replicanum folgt")
L(AH .. "CYCLE_BOSS", "Bosskampf folgt")

Would it be possible to change the English and French translations on the same model? Personally, I always have to take a moment to think when I have to distinguish between an arc and a cycle.

L(AH .. "ARC_BOSS", "Replicanum de Tho’at à venir")
L(AH .. "CYCLE_BOSS", "Phase de boss à venir")

I will test the arc_boss string length in game to be sure it fits.

**Comment by Flat-Badger-1971** [comment]
No problem - done in the version I've just pushed
