### ISSUE TITLE
Gw alarm is played when shared, without taking into account the setting

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#38]
https://github.com/Flat-Badger-1971/ArchiveHelper/blob/5cbbb03b1b3bb5eb11d2c24c862bd28e4834d9f4/misc/events.lua#L494

The PlayAlarm call should be done only if AH.Vars.GwPlay

**Comment by Flat-Badger-1971** [comment]
Ah yes, missed that one.
