### ISSUE TITLE
Bug: after getting the avatar transformation verse for the 4th time, a counter was displayed

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#39]
![Werewolf behemoth 2](https://github.com/Flat-Badger-1971/ArchiveHelper/assets/27444797/3d28ef7e-57d0-4055-a3f5-def48ff9b0b9)

**Comment by Stemuweb** [comment]
To be clear, I got the 3 visions.
Then a lucky streak and several times the Werewolf behemoth verse. The first times, the verse counter wasn't printed.

**Comment by Flat-Badger-1971** [comment]
How odd - a little tweak to the groupchat should sort that out - assuming transformation don't actually stack and make you extra werewolfy...

**Comment by Stemuweb** [comment]
I checked your change (while playing). I think you could even write it like this:

```
            if (avatar) then
               if (abilityType == AH.TYPES.VISION) the,
                  message = message .. " |cffff00(" .. ZO_CachedStrFormat(_G.ARCHIVEHELPER_COUNT, count, 3) .. ")|r"
               end
            elseif (count > 1 and) then
                message = message .. " |cffff00(" .. count .. ")|r"
            end
```
I'm not sure which one is the least difficult to read ;)

**Comment by Flat-Badger-1971** [comment]
Yeah, actually I prefer your version - it's better structured.

**Comment by Flat-Badger-1971** [comment]
OK - going to draw a line under this for now so I can get a release out. I'll close this issue - any future problems/ideas can go under new issues then.
