### ISSUE TITLE
Error update 43

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#42]
In french, when trying to select a verse at the end of a mobs stage.

It happens when the updated "fire orb" verse is one of the choices (happened twice to different players, in each case it was in the favorites). 

user:/AddOns/ArchiveHelper/misc/achievements.lua:103: attempt to index a nil value
stack traceback:
user:/AddOns/ArchiveHelper/misc/achievements.lua:103: in function 'AH.GetAbilityNeededForGeneralAchievement'
user:/AddOns/ArchiveHelper/ui/buffSelector.lua:66: in function 'AH.OnBuffSelectorShowing'
user:/AddOns/ArchiveHelper/misc/events.lua:90: in function 'onShowing'
[C]: in function 'PostHookFunction'
/EsoUI/Libraries/Utility/BaseObject.lua:306: in function 'ZO_DeferredInitializingObject:OnStateChanged'
/EsoUI/Libraries/Utility/BaseObject.lua:286: in function 'callback'
/EsoUI/Libraries/Utility/ZO_CallbackObject.lua:132: in function 'ZO_CallbackObjectMixin:FireCallbacks'
/EsoUI/Libraries/ZO_Scene/ZO_Scene.lua:151: in function 'ZO_Scene:SetState'
/EsoUI/Ingame/Scenes/InteractScene.lua:106: in function 'ZO_InteractScene:SetState'
/EsoUI/Libraries/ZO_Scene/ZO_SceneManager_Base.lua:207: in function 'ZO_SceneManager_Base:ShowScene'
/EsoUI/Libraries/ZO_Scene/ZO_SceneManager_Leader.lua:298: in function 'ZO_SceneManager_Leader:ShowScene'
/EsoUI/Libraries/ZO_Scene/ZO_SceneManager_Leader.lua:381: in function 'ZO_SceneManager_Leader:OnSceneStateHidden'
/EsoUI/Libraries/ZO_Scene/ZO_SceneManager_Base.lua:281: in function 'ZO_SceneManager_Base:OnSceneStateChange'
/EsoUI/Libraries/ZO_Scene/ZO_SceneManager_Leader.lua:328: in function 'ZO_SceneManager_Leader:OnSceneStateChange'
/EsoUI/Ingame/Scenes/IngameSceneManager.lua:398: in function 'ZO_IngameSceneManager:OnSceneStateChange'
/EsoUI/Libraries/ZO_Scene/ZO_Scene.lua:152: in function 'ZO_Scene:SetState'

**Comment by Flat-Badger-1971** [comment]
Just spotted that myself after running a couple of arcs. They changed the id they were using for some reason. Latest update should be fine (just released it)

⁣Get BlueMail for Android ​
