### ISSUE TITLE
Bugs in version 1.3.3

### ISSUE THREAD

**Issue by Stemuweb** [Flat-Badger-1971/ArchiveHelper#43]
1) The environment damage warning doesn't seem to work when the option is set to ON.

2) In french, some new options (account name and environment damage) are cut because too long. An easy fix would be to also define the string as the tooltip of the option so the whole string can be read when hovering with the pointer.

![Capture](https://github.com/user-attachments/assets/96f9f656-e29e-4968-93a9-e796be65e3ff)

3) In the treacherous crossing, you could withdraw the path '5 1 4 2 3'. After a few months of testing, it has not appeared anymore. It probably has been removed, because there is also a path "5 1 4 2 3 6'.

**Comment by Flat-Badger-1971** [comment]
All done. Thanks for you input.
